OPTIONS(SKIP=1)
LOAD DATA
INFILE 'C:\Users\linxu\Desktop\work\çÏã∆\database_scripts\import\info1\objects_CDBC01.csv'
INTO TABLE CDBC01_N1.objects
TRUNCATE
FIELDS TERMINATED BY ','
(OWNER,OBJECT_NAME,SUBOBJECT_NAME,OBJECT_ID,DATA_OBJECT_ID,OBJECT_TYPE,CREATED,LAST_DDL_TIME,TIMESTAMP,STATUS,TEMPORARY,GENERATED)
